Repository frenck/python-radios, pull requests merged in 2023-11, with the labels that each got.

#533 Update development toolchain
  .deepsource.toml
  .devcontainer/devcontainer.json
  .flake8
  .github/dependabot.yml
  .github/labels.yml
  .github/renovate.json
  .github/workflows/codeql.yaml
  .github/workflows/labels.yaml
  .github/workflows/linting.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release.yaml
  .github/workflows/stale.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  .nvmrc
  .pre-commit-config.yaml
  LICENSE.md
  README.md
  examples/ruff.toml
  package.json
  poetry.lock
  pyproject.toml
  sonar-project.properties
  src/radios/models.py
  src/radios/radio_browser.py
  tests/__init__.py
  tests/ruff.toml
  tests/test_radios.py
Labels: maintenance

#538 Replace pydantic with mashumaro
  poetry.lock
  pyproject.toml
  src/radios/models.py
  src/radios/radio_browser.py
  tests/test_radios.py
Labels: enhancement

#390 Add search option
  examples/example.py
  src/radios/radio_browser.py
Labels: new-feature, no-stale
